import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import metricsRouter from "./metrics";
import clientsRouter from "./clients";
import businessesRouter from "./businesses";
import keywordsRouter from "./keywords";
import clientAeoPlansRouter from "./client-aeo-plans";
import aeoPlansRouter from "./aeo-plans";
import sessionsRouter from "./sessions";
import devicesRouter from "./devices";
import proxiesRouter from "./proxies";
import plansRouter from "./plans";
import rankingReportsRouter from "./ranking-reports";
import rankingRunsRouter from "./ranking-runs";
import tasksRouter from "./tasks";
import dashboardRouter from "./dashboard";
import scalingRouter from "./scaling";
import farmMetricsRouter from "./farm-metrics";
import auditLogsRouter from "./audit-logs";
import packagesRouter from "./packages";
import onboardingRouter from "./onboarding";
import proofsRouter from "./proofs";
import keywordVariantsRouter from "./keyword-variants";
import analyticsRouter from "./analytics";
import llmRouter from "./llm";
import rankingsEmailRouter from "./rankings-email";
import portalRouter from "./portal";
import locationRouter from "./location";
import ingestRouter from "./ingest";
import salesRouter from "./sales";
import salesEmailRouter from "./sales-email";
import screenshotScanRouter from "./screenshot-scan";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/metrics", metricsRouter);
router.use("/clients", clientsRouter);
router.use("/businesses", businessesRouter);
router.use("/clients/:clientId/aeo-plans", clientAeoPlansRouter);
router.use("/aeo-plans", aeoPlansRouter);
router.use("/keywords", keywordsRouter);
router.use("/sessions", sessionsRouter);
router.use("/devices", devicesRouter);
router.use("/proxies", proxiesRouter);
router.use("/plans", plansRouter);
router.use("/ranking-reports", rankingReportsRouter);
router.use("/ranking-runs", rankingRunsRouter);
router.use("/tasks", tasksRouter);
router.use("/dashboard", dashboardRouter);
router.use("/scaling", scalingRouter);
router.use("/farm-metrics", farmMetricsRouter);
router.use("/audit-logs", auditLogsRouter);
router.use("/packages", packagesRouter);
router.use("/onboarding", onboardingRouter);
router.use("/proofs", proofsRouter);
router.use(keywordVariantsRouter);
router.use("/analytics", analyticsRouter);
router.use("/llm", llmRouter);
router.use("/rankings", rankingsEmailRouter);
router.use("/portal", portalRouter);
router.use("/location", locationRouter);
router.use("/ingest", ingestRouter);
router.use("/sales", salesRouter);
router.use("/sales", salesEmailRouter);
router.use("/screenshot-scan", screenshotScanRouter);

export default router;
